### ISSUE TITLE
I've been waiting for 2 hours, it's not confirmed, bitcoin isn't going

### ISSUE THREAD

**Issue by Coskunkolay** [muun/apollo#108]
I've been waiting for 2 hours, it's not confirmed, bitcoin isn't going o clock 16.14 
18.29 why? 
!
![Screenshot_20230123_182834_io muun apollo](https://user-images.githubusercontent.com/106901607/214079397-798d771e-7785-48ba-95f6-351f322261fc.jpg)

**Comment by acrespo** [comment]
Hi there!

Thanks for writing us! This is probably due to the recipient not revealing the payment preimage (It's likely that the person you are trying to pay to is not online or has signed out from their wallet), though I would need more information to actually confirm the issue. If that's the case the payment will eventually fail and you will get back the amount of the payment. 
If you don't mind sharing the information about the payment (and the lightning service or node you are trying to send the payment to) I can check out what specifically happen (it can be privately, contacting us to [support@muun.com](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=support@muun.com)).

**Comment by Coskunkolay** [comment]
Thank you, I sent it in the mail in the evening, friends made a direct return, yes my payment came back to my account, thank you for your interest, I'm just trying to understand walleti 😊😊
