### ISSUE TITLE
Funds stuck in the wallet

### ISSUE THREAD

**Issue by Darth-Coin** [muun/apollo#14]
Guys, I've sent you an email about an issue with funds stuck in the wallet. But seems that you ignore it.
Recently I wanted to test your Muun wallet. But funny things happen.
1st intent:
-	I created a new wallet yesterday
-	a friend sent me a test of 100 sats on LN to my Muun. All OK
-	I sent those 100 sats to another of my LN wallets, with 0 fee (I couldn't believe it).
-	Then I deleted the wallet

2nd intent:
-	Then I recovered and old Muun wallet, created 2 months ago, to see how the recovery works. All OK
-	I sent from my node in 2 txs, through LN 150k sats. All OK received.
-	I wanted to send those sats to another LN wallet, all the balance at once. 
o	LNURL is NOT supported
o	Payment invoice request from Phoenix without specific amount is not supported
o	Payment invoice request from Phoenix wallet with amount is supported but is charging 75% fee ! This is insane
-	I wanted to send all balance to an onchain wallet:
o	The fee is 25% - unacceptable in the conditions when the mempool is at medium level fees of 20sat/vB

I tried again to send just 50k sats to a Bluewallet invoice. No success after almost 1min waiting wheel, is getting an error (see attached images).

So now I am stuck. I can’t move those funds from Muun with a decent amount of fee.
Guys this is insane, how is possible that on LN I would pay 3 times the fee than onchain tx, for the same amount?
Please advise. Is there a way to import this wallet into Electrum?

Here attached some errors
![muun_exorbitant_fee](https://user-images.githubusercontent.com/56997124/110985663-01373000-836d-11eb-8f6f-c478caa8efec.jpg)
![muun_lnurl_not_supported](https://user-images.githubusercontent.com/56997124/110985668-02685d00-836d-11eb-9f55-4cec352006e3.jpg)
![muun_invoice_error](https://user-images.githubusercontent.com/56997124/110986188-a2be8180-836d-11eb-88d7-32d39f22513d.jpg)

**Comment by florravenna** [comment]
Hi, thanks for reaching out. 

I'm sorry to hear we didn't answer your email. We are very careful to answer all messages we received, so we probably missed it. Anyway, I'm happy to answer you here:

- LNURL: We're currently working on adding support for LNURL. It will be ready in the next few months.

- Invoices with no specific amount: We definitely want to support paying invoices with no specific amount. This will take a bit longer, but we'll work on it.

- Lightning payments with a higher fee: while most payments in Lightning can be made 100% off-chain with lower fees, Lightning still requires the occasional use of on-chain transactions with higher fees. Normally, we manage to keep the on-chain fee low, and the off-chain payment is settled instantly. However, if the amount sent is larger (>45 USD approximately), it will probably trigger a next-block-fee transaction, for fast confirmation. This is the reason why this off-chain payment has way higher fees. I suggest you make smaller lightning payments instead (on-chain transactions will trigger eventually, but with lower fees). We're constantly working on our Lightning implementation to reduce the on-chain hits, making all payments cheaper and faster.

- Withdrawing to an on-chain wallet: when you do this, the transaction is on-chain and not proportional to the amount being sent. Did you get to edit the network fee and choose how much to pay?

- Error report: would you mind sharing this report with us, or contacting me (florencia@muun.com) by email so that I can search your previous email in my inbox? Can't find it without knowing your email address.

Thank you, and sorry for the inconvenience.

**Comment by Darth-Coin** [comment]
So, Florencia, I sent you an email response on 12 March and I still didn't received any solution. Not even here an answer.
I am done with wallet. Will never mention this wallet to anybody.
WORST EXPERIENCE EVER HAD WITH A BITCOIN WALLET IN ALL THESE 8+ YEARS USING BITCOIN.

**Comment by florravenna** [comment]
Hi again,  

Here are two different ways your can swipe your funds:

- Make an on-chain transaction to a bitcoin address, and pick the exact fee you want to pay. 
- Make smaller lightning payments. An on-chain transaction might trigger anyway (it depends on your liquidity) but if payments are small enough (<45 USD) the wallet will manage to keep them pretty low.

You can do this during the weekend and save on fees. https://mempool.space/ https://muun.com/#fees

I'm sorry to see you had a bad experience. I really tried to help you out. We'll keep working to make it better.

**Comment by esneider** [comment]
Hey @Darth-Coin, it appears your emails were going to the spam folder. We are really sorry about that.

Already answered via email, let me know if there's anything else we can help with.

**Comment by esneider** [comment]
I'll close this until new information appears.
