### ISSUE TITLE
Use /bin/sh instead of /bin/bash if possible in scripts

### ISSUE THREAD

**Issue by emanuelb** [muun/apollo#15]
The 2 scripts in ./tools/ directory use `#!/bin/bash` it's better to use `#!/bin/sh` instead if possible (to avoid bash dependency if not needed, script will work by running using other shells)

**Comment by federicobond** [comment]
Hi @emanuelb, thanks for your input. We decided to run those in bash since it is ubiquitous on modern systems and gives us a consistent language to work with in both macOS and Linux. [Google's shell style guide](https://google.github.io/styleguide/shellguide.html), for example, adopts the same choice.

If you are having trouble running the scripts on a certain system due to this, please let us know.

**Comment by emanuelb** [comment]
Then you at least should add the bash dependency requirement into the building section, currently I didn't managed to compile the app at all (many failures to install the libwallet dep), will open issue with details soon.
most of the time I start with Containerfile that use alpine as base which don't include bash, for many android apps the dependency is not needed and can be avoided (like upgrading the gradlew scripts which use sh instead of bash, and change simple scripts to use it instead of bash if there is no bashisms in the script)

**Comment by emanuelb** [comment]
Opened issue about build failures in #16 which include Containerfile that can remove the bash dependency installation if /bin/sh are used instead of bash, anyway I reported issues like this in the past & they got fixed, for example this bug which affect probably every react-native build:  https://github.com/react-native-community/cli/issues/1090 my advice is always to use /bin/sh instead of bash if it's possible (the script itself don't use bash specific features, also changing to sh if run via bash still works, so different shell need to be tested, also checkbashisms tool help to catch some of the related issues)
