### ISSUE TITLE
Wallet taking fees on failed txs

### ISSUE THREAD

**Issue by grunch** [muun/apollo#62]
Hey guys, yesterday something weird happened to me and I wanted to know what it is.

I received a lightning payments of 480000 sats, then I tried to do two payments, the first one was 451817 sats payment, it failed, then another one of 420000 sats and that one failed again, the curious thing was that it subtracted me both fees, 200 from the first one and 263 from the second one, why this is happening? I attach screenshots, to see the sequence easily.

![photo_2021-12-04_11-58-02](https://user-images.githubusercontent.com/228364/144714288-8b4556f7-adec-4226-802f-fd6da9da49a7.jpg)

first payment that I tried to do failed
![photo_2021-12-04_11-58-13](https://user-images.githubusercontent.com/228364/144714298-5771c2ed-2f91-4d32-9621-e858d56cd729.jpg)

Second payment failed
![photo_2021-12-04_11-58-10](https://user-images.githubusercontent.com/228364/144714315-2207880a-f202-4149-b4e7-ae5e7703e514.jpg)

Current balance
![photo_2021-12-04_11-58-07](https://user-images.githubusercontent.com/228364/144714323-7ef4817e-5680-46e1-a5c9-070ece0f9590.jpg)

**Comment by acrespo** [comment]
Hi there grunch!

We’re sorry you’ve experienced this ugly surprise but this is actually the current expected behavior. Let me explain. You see, in our current lightning implementation, some lightning payments require an on-chain transactioon (ie submarine swap). This is most likely to happen when big amounts are sent via LN. The network fees of those payments tell us that a on-chain transaction is/was required. Since the payment failed, you are refunded the payment amount and the lightning network fee portion of the fees, but since an on-chain transaction was created, its not possible to refund the network fee associated with it.

I hope this brings some clarity. We are aware this is a painful experience and we are working on improving our lightning implementation to move away from our current “all funds on-chain” approach and towards an “all funds off-chain” approach which will handle these edge case much better.

**Comment by grunch** [comment]
Hi, thanks for the response, I undestand, it makes sense, so probably is not a good idea to use muun to send big lightning payments, right? at least not until you migrate to off-chain, I am closing this issue, keep up the hard work 😄
