### ISSUE TITLE
enable wallet sync with koinly

### ISSUE THREAD

**Issue by vncs1880** [muun/apollo#79]
is there an integration available for services such koinly.io app or maybe some workaround to enable wallet sync. sorry if this is not the proper place to ask

**Comment by acrespo** [comment]
Hi there! 

Thanks for your feedback! We'd love to tackle this and make tax reporting easier for everyone. The problem is this varies significantly depending on the region and lightning make this kind of task harder (e.g not just a matter of exporting an xpub). Since we are still a small team, we try to stay focused on bringing the most value to the greatest amount of people, which normally means having a global approach. 

I'll let the product team about your request and add your +1 (you're not the first to ask for something like this 😉).

**Comment by vncs1880** [comment]
sure not a biggie thx

**Comment by vncs1880** [comment]
sure not a biggie thx
